# Fonte e dicionário dos dados

Série A masculina 2025, rodadas oficiais 1–38. Unidade coletiva; dados reais OpenFootball CC0.

In [1]:
import json
from pathlib import Path
import pandas as pd
root = Path.cwd()
document = json.loads((root / "data/analytics/collective.json").read_text(encoding="utf-8"))
facts = pd.DataFrame(document["team_matches"])
clubs = pd.DataFrame(document["club_totals"])
flamengo = facts[facts.club_id == "club:flamengo"]

In [2]:
print(document["source"])
print(document["coverage"])
pd.DataFrame(document["matches"]).head()

{'source_id': 'openfootball:football-json', 'url': 'https://raw.githubusercontent.com/openfootball/football.json/e6744429ee395bc86f247348c6184bb08d4eb361/2025/br.1.json', 'revision': 'e6744429ee395bc86f247348c6184bb08d4eb361', 'license': 'CC0-1.0', 'sha256': '0fcc4647256b2e1f58b50f1372b751aeb7e6aacb5b8cd747579dd7ab71303fbb', 'collected_at': '2026-10-21T19:49:47.560647+00:00', 'license_url': 'https://github.com/openfootball/football.json/blob/e6744429ee395bc86f247348c6184bb08d4eb361/LICENSE.md'}
{'status': 'verified', 'matches': 380, 'clubs': 20, 'rounds': 38, 'matches_per_round': 10, 'matches_per_club': 38, 'flamengo_matches': 38, 'duplicates': 0, 'missing_scores': 0, 'removed_rows': 0, 'official_mapping': 'round_labels_from_openfootball_not_cbf_match_ids'}

,match_id,competition_id,season,official_round,date,home_id,away_id,home_name,away_name,home_goals,away_goals,source_locator,external_match_id,source_id,collected_at
0,1998aa5e-1417-5daa-bb07-9a94f76e1c20,competition:brasileirao-serie-a-men,2025,1,2025-03-29,club:fortaleza,club:fluminense,Fortaleza,Fluminense,2,0,matches[3],None,openfootball:football-json,2026-10-21T19:49:47.560647+00:00
1,25a52e04-e3e1-5ef7-b7ba-44e8204cffdf,competition:brasileirao-serie-a-men,2025,1,2025-03-29,club:gremio,club:atletico-mg,Grêmio,Atlético-MG,2,1,matches[2],None,openfootball:football-json,2026-10-21T19:49:47.560647+00:00
2,3a60ee8e-594f-53e2-843a-3d073034b2da,competition:brasileirao-serie-a-men,2025,1,2025-03-29,club:sao-paulo,club:sport,São Paulo,Sport,0,0,matches[0],None,openfootball:football-json,2026-10-21T19:49:47.560647+00:00
3,6de27c51-3546-5445-980d-12316cde473d,competition:brasileirao-serie-a-men,2025,1,2025-03-31,club:bragantino,club:ceara,Bragantino,Ceará,2,2,matches[9],None,openfootball:football-json,2026-10-21T19:49:47.560647+00:00
4,76a89d09-dd7b-55a6-9fc2-2ffe15074b62,competition:brasileirao-serie-a-men,2025,1,2025-03-30,club:vasco,club:santos,Vasco,Santos,2,1,matches[7],None,openfootball:football-json,2026-10-21T19:49:47.560647+00:00

In [3]:
pd.DataFrame(document["matches"]).dtypes.astype(str).to_frame("tipo")

                     tipo
match_id              str
competition_id        str
season              int64
official_round      int64
date                  str
home_id               str
away_id               str
home_name             str
away_name             str
home_goals          int64
away_goals          int64
source_locator        str
external_match_id  object
source_id             str
collected_at          str

OpenFootball CC0. Cada partida gera dois registros clube × partida. Identificadores internos não são IDs CBF. Somente placares e resultados permitem os indicadores deste trabalho.